#
#  Copyright (c) 2018-2021 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: codeready-workspaces
spec:
  server:
    useInternalClusterSVCNames: true
    cheImage: ''
    cheImageTag: ''
    devfileRegistryImage: ''
    pluginRegistryImage: ''
    cheFlavor: codeready
    cheClusterRoles: ''
    cheWorkspaceClusterRole: ''
    serverTrustStoreConfigMapName: ''
    gitSelfSignedCert: false
    tlsSupport: true
    proxyURL: ''
    proxyPort: ''
    proxyUser: ''
    proxyPassword: ''
    nonProxyHosts: ''
    serverMemoryRequest: ''
    serverMemoryLimit: ''
    workspaceNamespaceDefault: ''
    allowUserDefinedWorkspaceNamespaces: false
    serverExposureStrategy: ''
    singleHostGatewayImage: ''
    singleHostGatewayConfigSidecarImage: ''
    singleHostGatewayConfigMapLabels: {}
  database:
    externalDb: false
    chePostgresHostName: ''
    chePostgresPort: ''
    chePostgresUser: ''
    chePostgresPassword: ''
    chePostgresDb: ''
    postgresImage: ''
  storage:
    pvcStrategy: per-workspace
    pvcClaimSize: 1Gi
    preCreateSubPaths: true
    pvcJobsImage: ''
    postgresPVCStorageClassName: ''
    workspacePVCStorageClassName: ''
  auth:
    externalIdentityProvider: false
    identityProviderURL: ''
    identityProviderAdminUserName: admin
    identityProviderPassword: admin
    identityProviderRealm: ''
    identityProviderClientId: ''
    oAuthClientName: ''
    oAuthSecret: ''
    identityProviderImage: ''
  metrics:
    enable: true
